// theme constant
export const gridSpacing = 3;
export const drawerWidth = 260;

export const states = [
  { value: "", label: "Selecionar" },
  { value: "AC", label: "Acre" },
  { value: "AL", label: "Alagoas" },
  { value: "AP", label: "Amapá" },
  { value: "AM", label: "Amazonas" },
  { value: "BA", label: "Bahia" },
  { value: "CE", label: "Ceará" },
  { value: "DF", label: "Distrito Federal" },
  { value: "ES", label: "Espírito Santo" },
  { value: "GO", label: "Goiás" },
  { value: "MA", label: "Maranhão" },
  { value: "MT", label: "Mato Grosso" },
  { value: "MS", label: "Mato Grosso do Sul" },
  { value: "MG", label: "Minas Gerais" },
  { value: "PA", label: "Pará" },
  { value: "PB", label: "Paraíba" },
  { value: "PR", label: "Paraná" },
  { value: "PE", label: "Pernambuco" },
  { value: "PI", label: "Piauí" },
  { value: "RJ", label: "Rio de Janeiro" },
  { value: "RN", label: "Rio Grande do Norte" },
  { value: "RS", label: "Rio Grande do Sul" },
  { value: "RO", label: "Rondônia" },
  { value: "RR", label: "Roraima" },
  { value: "SC", label: "Santa Catarina" },
  { value: "SP", label: "São Paulo" },
  { value: "SE", label: "Sergipe" },
  { value: "TO", label: "Tocantins" },
];
// export const logradouros = ["Av.", "Praça", "Rua", "Travessa"];
export const logradouros = [
  { value: "Área" },
  { value: "Acesso" },
  { value: "Acampamento" },
  { value: "Acesso Local" },
  { value: "Adro" },
  { value: "Área Especial" },
  { value: "Aeroporto" },
  { value: "Alameda" },
  { value: "Avenida Marginal Direita" },
  { value: "Avenida Marginal Esquerda" },
  { value: "Anel Viário" },
  { value: "Antiga Estrada" },
  { value: "Artéria" },
  { value: "Alto" },
  { value: "Atalho" },
  { value: "Área Verde" },
  { value: "Avenida" },
  { value: "Avenida Contorno" },
  { value: "Avenida Marginal" },
  { value: "Avenida Velha" },
  { value: "Balneário" },
  { value: "Beco" },
  { value: "Buraco" },
  { value: "Belvedere" },
  { value: "Bloco" },
  { value: "Balão" },
  { value: "Blocos" },
  { value: "Bulevar" },
  { value: "Bosque" },
  { value: "Boulevard" },
  { value: "Baixa" },
  { value: "Cais" },
  { value: "Calçada" },
  { value: "Caminho" },
  { value: "Canal" },
  { value: "Chácara" },
  { value: "Chapadão" },
  { value: "Ciclovia" },
  { value: "Circular" },
  { value: "Conjunto" },
  { value: "Conjunto Mutirão" },
  { value: "Complexo Viário" },
  { value: "Colônia" },
  { value: "Comunidade" },
  { value: "Condomínio" },
  { value: "Corredor" },
  { value: "Campo" },
  { value: "Córrego" },
  { value: "Contorno" },
  { value: "Descida" },
  { value: "Desvio" },
  { value: "Distrito" },
  { value: "Entre Bloco" },
  { value: "Estrada Intermunicipal" },
  { value: "Enseada" },
  { value: "Entrada Particular" },
  { value: "Entre Quadra" },
  { value: "Escada" },
  { value: "Escadaria" },
  { value: "Estrada Estadual" },
  { value: "Estrada Vicinal" },
  { value: "Estrada de Ligação" },
  { value: "Estrada Municipal" },
  { value: "Esplanada" },
  { value: "Estrada de Servidão" },
  { value: "Estrada" },
  { value: "Estrada Velha" },
  { value: "Estrada Antiga" },
  { value: "Estação" },
  { value: "Estádio" },
  { value: "Estância" },
  { value: "Estrada Particular" },
  { value: "Estacionamento" },
  { value: "Evangélica" },
  { value: "Elevada" },
  { value: "Eixo Industrial" },
  { value: "Favela" },
  { value: "Fazenda" },
  { value: "Ferrovia" },
  { value: "Fonte" },
  { value: "Feira" },
  { value: "Forte" },
  { value: "Galeria" },
  { value: "Granja" },
  { value: "Núcleo Habitacional" },
  { value: "Ilha" },
  { value: "Indeterminado" },
  { value: "Ilhota" },
  { value: "Jardim" },
  { value: "Jardinete" },
  { value: "Ladeira" },
  { value: "Lagoa" },
  { value: "Lago" },
  { value: "Loteamento" },
  { value: "Largo" },
  { value: "Lote" },
  { value: "Mercado" },
  { value: "Marina" },
  { value: "Modulo" },
  { value: "Projeção" },
  { value: "Morro" },
  { value: "Monte" },
  { value: "Núcleo" },
  { value: "Núcleo Rural" },
  { value: "Outeiro" },
  { value: "Paralela" },
  { value: "Passeio" },
  { value: "Pátio" },
  { value: "Praça" },
  { value: "Praça de Esportes" },
  { value: "Parada" },
  { value: "Paradouro" },
  { value: "Ponta" },
  { value: "Praia" },
  { value: "Prolongamento" },
  { value: "Parque Municipal" },
  { value: "Parque" },
  { value: "Parque Residencial" },
  { value: "Passarela" },
  { value: "Passagem" },
  { value: "Passagem de Pedestre" },
  { value: "Passagem Subterrânea" },
  { value: "Ponte" },
  { value: "Porto" },
  { value: "Quadra" },
  { value: "Quinta" },
  { value: "Quintas" },
  { value: "Rua" },
  { value: "Rua Integração" },
  { value: "Rua de Ligação" },
  { value: "Rua Particular" },
  { value: "Rua Velha" },
  { value: "Ramal" },
  { value: "Recreio" },
  { value: "Recanto" },
  { value: "Retiro" },
  { value: "Residencial" },
  { value: "Reta" },
  { value: "Ruela" },
  { value: "Rampa" },
  { value: "Rodo Anel" },
  { value: "Rodovia" },
  { value: "Rotula" },
  { value: "Rua de Pedestre" },
  { value: "Margem" },
  { value: "Retorno" },
  { value: "Rotatória" },
  { value: "Segunda Avenida" },
  { value: "Sitio" },
  { value: "Servidão" },
  { value: "Setor" },
  { value: "Subida" },
  { value: "Trincheira" },
  { value: "Terminal" },
  { value: "Trecho" },
  { value: "Trevo" },
  { value: "Túnel" },
  { value: "Travessa" },
  { value: "Travessa Particular" },
  { value: "Travessa Velha" },
  { value: "Unidade" },
  { value: "Via" },
  { value: "Via Coletora" },
  { value: "Via Local" },
  { value: "Via de Acesso" },
  { value: "Vala" },
  { value: "Via Costeira" },
  { value: "Viaduto" },
  { value: "Via Expressa" },
  { value: "Vereda" },
  { value: "Via Elevado" },
  { value: "Vila" },
  { value: "Viela" },
  { value: "Vale" },
  { value: "Via Litorânea" },
  { value: "Via de Pedestre" },
  { value: "Variante" },
  { value: "Zigue-Zague" },
];
