-- CreateTable
CREATE TABLE "Radiation" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "LONGITUDE" REAL NOT NULL,
    "LATITUDE" REAL NOT NULL,
    "JANEIRO" REAL NOT NULL,
    "FEVEREIRO" REAL NOT NULL,
    "MARCO" REAL NOT NULL,
    "ABRIL" REAL NOT NULL,
    "MAIO" REAL NOT NULL,
    "JUNHO" REAL NOT NULL,
    "JULHO" REAL NOT NULL,
    "AGOSTO" REAL NOT NULL,
    "SETEMBRO" REAL NOT NULL,
    "OUTUBRO" REAL NOT NULL,
    "NOVEMBRO" REAL NOT NULL,
    "DEZEMBRO" REAL NOT NULL,
    "ANUAL" REAL NOT NULL,
    "PRIMAVERA" REAL NOT NULL,
    "VERAO" REAL NOT NULL,
    "OUTONO" REAL NOT NULL,
    "INVERNO" REAL NOT NULL
);
